### ISSUE TITLE
way to preprocess files (compile hbs)

### ISSUE THREAD

**Issue by lifeart** [izelnakri/qunitx#31]
Right now I get this error:
![image](https://user-images.githubusercontent.com/1360552/139850711-1c7b1123-7d9f-4276-b396-ce8d30f1983d.png)

If I'm trying to execute test like this:

```js
import { module, test } from 'qunitx';
import { renderComponent } from '@glimmerx/core';

import Icon from './../components/Icon';

async function render(component, args = {}) {
  await renderComponent(component, {
    element: document.getElementById('qunit-fixture'),
    args: args
  })
}

module('Basic sanity check', function (hooks) {
  test('it works', async function (assert) {
    await render(Icon, { bgColor: 'blue '});
    assert.equal(true, true);
  });
});
```

**Comment by izelnakri** [comment]
Yes, glimmerx doesn't provide an actual runtime hbs compilation, they do that in their webpack babel plugin magic. I suggest using emberx package instead. Closing this issue, let me know if you'd like it to be reopened.
